🐛 Skip sleep for not signed Tx, estimate gas by data size, and update sequence when code 32 happened
likecoin/iscn-batch-uploader pull request #6
Opened 2021-08-31 12:19 UTC by WeiJun0827

Fix #5

2021-08-31 13:47 UTC, shellyYG requested changes

2021-08-31 13:47 UTC, shellyYG commented on util/iscn.js
> +  const gasFee = gas.multipliedBy(DEFAULT_GAS_PRICE_NUMBER);
should not multiply DEFAULT_GAS_PRICE_NUMBER

2021-09-01 11:35 UTC, shellyYG approved these changes

2021-09-01 11:35 UTC, shellyYG commented on util/iscn.js
> +  const gasFee = gas.multipliedBy(DEFAULT_GAS_PRICE_NUMBER);
sorry my bad, correct to multiply gas price

2021-09-01 12:49 UTC, williamchong requested changes

2021-09-01 12:49 UTC, williamchong commented on index.js
>            await sleep(15000);
Can we refetch sequence after sleep()?

2021-09-01 16:00 UTC, williamchong approved these changes

2021-09-15 09:01 UTC, merged